#!/bin/bash
set -xe
unset http_proxy

checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 2 8 9 "$@"

# create Cycles input folder and copy base files
mkdir -p input
#copy the crop file to the input directory
cp $INPUTS2 input/
#extract the zipfile into the input directory
unzip "$INPUTS1" -d input

#obtain the file of weather and soil file
pushd input
weather=$(find . -name *.weather -printf "%f\n")
soil=$(find . -name *.soil -printf "%f\n")
popd
#backup the input that we are going to use in the future
cp -r input/ input_future/

# run cycles baseline
python3 cycles-wrapper.py --start-year $PARAMS1 --end-year $PARAMS2 --baseline True --crop $PARAMS3 --start-planting-date 100 --end-planting-date 0 --fertilizer-rate 156.25 --weed-fraction $PARAMS7 --forcing $PARAMS8 --weather-file $weather $INPUTS2 $soil
checkExitCode

# clean up folders and prepare input folder for cycles run
mv input_future input
mv output/cycles-run/reinit.dat input/cycles.reinit
rm -rf output

# # run cycles
python3 cycles-wrapper.py --start-year $PARAMS1 --end-year $PARAMS2 --baseline False --crop $PARAMS3 --start-planting-date $PARAMS4 --end-planting-date $PARAMS5 --fertilizer-rate $PARAMS6 --weed-fraction $PARAMS7 --forcing $PARAMS8 --reinit-file cycles.reinit --weather-file $weather $INPUTS2 $soil
checkExitCode

# IMPORTANT: temporary hack for saving input/output data into local folder
mkdir outputs
cp -R input/ outputs/
cp -R output/ outputs/
zip -r outputs.zip outputs/
mv outputs.zip $OUTPUTS9

# moving and renaming output data
mv output/cycles-run/annualSoilProfileC.dat $OUTPUTS1
mv output/cycles-run/annualSOM.dat $OUTPUTS2
mv output/cycles-run/$PARAMS3.dat $OUTPUTS3
mv output/cycles-run/N.dat $OUTPUTS4
mv output/cycles-run/season.dat $OUTPUTS5
mv output/cycles-run/summary.dat $OUTPUTS6
mv output/cycles-run/weather.dat $OUTPUTS7
mv output/cycles-run/water.dat $OUTPUTS8
